In [28]:
import numpy as np

matrizA = np.random.randint(10, size=(3, 3))

print(matrizA)

determinante = round((np.linalg.det(matrizA)),2)

determinante1 = round(determinante,2)
print(determinante)
print(determinante1)

[[5 3 1]
 [7 1 7]
 [8 1 6]]
36.0
36.0


In [43]:
import numpy as np

num_corredores = 6
num_voltas = 10

velocidade = np.random.uniform(60, size = (6, 10))

velocidade = np.round(velocidade, 3)

print(velocidade)

[[58.129 47.832  5.007 23.188 35.983 44.651 10.621 16.195 44.697 36.655]
 [40.241 37.001 44.398 28.317 34.504 28.975 54.478 24.446 57.109 47.362]
 [57.026 27.042  2.637 50.898 17.794 40.1   50.963 58.252  9.352 58.794]
 [11.168 24.534 29.053 53.872 44.267 21.087 45.612  5.926 44.029 44.206]
 [ 2.307 53.68  16.493 35.511  8.689 50.822 21.252 53.404 45.67  42.989]
 [58.949  7.179 16.95  42.474 37.973 27.776 59.356 59.653 49.467 41.792]]


In [55]:
melhorVolta = 60
classificacaoFinal = 0

for i in range(num_corredores):
  for j in range(num_voltas):
    if velocidade[i][j] < melhorVolta:
      melhorVolta = velocidade[i][j]

corredorMaisRapido = np.where(velocidade == melhorVolta)[0][0]
numVolta = np.where(velocidade == melhorVolta)[0][0]

print(f'Com uma volta de {melhorVolta} segundo, o corredor {corredorMaisRapido + 1} foi o melhor.')
print(numVolta)


Com uma volta de 2.307 segundo, o corredor 5 foi o melhor.
4
