In [ ]:
import numpy as np

matrizA = np.random.randint(10, size=(3, 3))

print(matrizA)

determinante = round((np.linalg.det(matrizA)),2)

determinante1 = round(determinante,2)
print(determinante)
print(determinante1)

[[5 3 1]
 [7 1 7]
 [8 1 6]]
36.0
36.0


In [107]:
#Criando uma matriz 6 x 10, onde 6 é o número de corredores e 10 o número de voltas

import numpy as np

numCorredores = 6
numVoltas = 10

velocidade = np.random.uniform(100, size = (numCorredores, numVoltas))
velocidade = np.round(velocidade, 4)

print(velocidade)

[[94.6649 34.1727 71.5044 10.0126 85.4749 40.5546  9.5289 53.8904 74.6661
   9.5963]
 [12.1653  2.3272 24.001  33.024  83.9798 91.6761 52.6295 96.2162 30.3603
  81.6366]
 [75.5911 10.3963 84.7191 16.6177 56.1245 73.8793 51.8267 21.4931 56.6397
  11.8691]
 [ 1.7868 69.0191 67.9905 35.8067 24.2226 19.7627 66.0619 64.7107  2.5849
  26.4156]
 [36.8946 76.6681 38.3226 95.0449 55.8677 22.0133 49.792  65.9301  8.0654
  95.2656]
 [61.7067 90.9214 81.3816 69.0264 89.6586  5.8176 10.339  38.3784 58.5548
  68.8906]]


In [102]:
# Informar o tempo da volta mais rápida
tempoVoltaMaisRapida = np.min(velocidade)
print(tempoVoltaMaisRapida)

# Infomar o índice da volta mais rápida
numVoltaMaisRapida = velocidade.argmin()
print(numVoltaMaisRapida)

# Convertendo o índice em posição de X e Y
corredor = numVoltaMaisRapida // numVoltas
print(corredor)

volta = numVoltaMaisRapida % numVoltas
print(volta)

1.0192
30
3
0


In [126]:
# Somando as voltas de cada corredor
totalTempoCorredor = np.sum(velocidade, axis=1)
print(totalTempoCorredor)

# Verificando o corredor mais rápido e o tempo total da corrida
campeao = totalTempoCorredor.argmin()
print(campeao)

tempoCampeao = np.min(totalTempoCorredor)

tempoCampeao = round(tempoCampeao, 4)
print(tempoCampeao)



[484.0658 508.016  459.1566 378.3615 543.8643 574.6751]
3
378.3615


In [149]:
# Criar classificação

classificacao = np.argsort(totalTempoCorredor)

# Resultado
print('********** MELHOR TEMPO **********')
print(f'Volta mais rápida: {volta +1}ª\n Tempo: {tempoVoltaMaisRapida * 60} segundos\n Corredor: {corredor}\n')
print()
print('************ CLASSIFICAÇÃO ************')
print('COLOCAÇÃO | CORREDOR      |   TEMPO')
print('---------------------------------------')
for i in range(numCorredores):
  print(f'{i+1}º        |      0{classificacao[i]+1}       | {totalTempoCorredor[i] * 60:.4f}')


********** MELHOR TEMPO **********
Volta mais rápida: 1ª
 Tempo: 61.15200000000001 segundos
 Corredor: 3


************ CLASSIFICAÇÃO ************
COLOCAÇÃO | CORREDOR      |   TEMPO
---------------------------------------
1º        |      04       | 29043.9480
2º        |      03       | 30480.9600
3º        |      01       | 27549.3960
4º        |      02       | 22701.6900
5º        |      05       | 32631.8580
6º        |      06       | 34480.5060
